language: cpp

compiler:
- clang

os:
- linux

before_script:
  - wget https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.sh
  - chmod +x cmake-3.16.4-Linux-x86_64.sh
  - ./cmake-3.16.4-Linux-x86_64.sh --skip-license --prefix /usr/
  - mkdir build
  - cd build
  - cmake ..
  - make enable-debug
  - make enable-test

script:
  - make
  - ./bin/symbolic_test
  - make coverage
